name: Build and Test Executables

on:
  push:
    tags:
      - 'v*'

# Add permissions block
permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          # Install dependencies that PyInstaller needs to include
          pip install dropbox python-dotenv
          # Build with all dependencies
          pyinstaller --onefile --name dropbox-renamer --hidden-import=dropbox --hidden-import=dotenv dropbox_renamer/rename_files_with_date.py
      - name: Create distribution zip
        run: |
          # Create a distribution directory
          mkdir dist\dropbox-renamer-windows
          # Copy the executable
          copy dist\dropbox-renamer.exe dist\dropbox-renamer-windows\
          # Copy the Windows README
          copy README.windows.md dist\dropbox-renamer-windows\README.md
          # Create the zip file
          Compress-Archive -Path dist\dropbox-renamer-windows\* -DestinationPath dist\dropbox-renamer-windows.zip
          # List files to verify
          dir dist
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/dropbox-renamer-windows.zip
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Dropbox Renamer ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            dist/dropbox-renamer-windows.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable
        run: |
          # Install dependencies that PyInstaller needs to include
          pip install dropbox python-dotenv
          # Build with all dependencies
          pyinstaller --onefile --name dropbox-renamer --hidden-import=dropbox --hidden-import=dotenv dropbox_renamer/rename_files_with_date.py
      - name: Create distribution zip
        run: |
          # Create a distribution directory
          mkdir -p dist/dropbox-renamer-macos
          # Copy the executable
          cp dist/dropbox-renamer dist/dropbox-renamer-macos/
          # Copy the Mac README
          cp README.mac.md dist/dropbox-renamer-macos/README.md
          # Make the executable executable
          chmod +x dist/dropbox-renamer-macos/dropbox-renamer
          # Create the zip file
          cd dist && zip -r dropbox-renamer-macos.zip dropbox-renamer-macos
          # List files to verify
          ls -la
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: dist/dropbox-renamer-macos.zip
      - name: Add to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          files: |
            dist/dropbox-renamer-macos.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-windows:
    needs: build-windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-executable
          path: .
      - name: Extract zip
        run: |
          Expand-Archive -Path dropbox-renamer-windows.zip -DestinationPath test-files -Force
      - name: Test executable
        run: |
          cd test-files
          dir
          # Test with --help flag
          .\dropbox-renamer.exe --help 